pipeline:
  name: Build gabs-redlock-demo
  identifier: Build_gacerioni_gabs_redlock_demo_1708038145151
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - stepGroup:
                  name: Redis Background Group
                  identifier: Redis_Background_Group
                  steps:
                    - step:
                        type: Background
                        name: Redis Stack
                        identifier: redis
                        spec:
                          connectorRef: gabsdh
                          image: redis:7.2.4
                          shell: Sh
                          portBindings:
                            "6379": "6379"
                          imagePullPolicy: IfNotPresent
              - step:
                  type: Run
                  name: Get Python App Version
                  identifier: Get_Python_App_Version
                  spec:
                    connectorRef: gabsdh
                    image: python:3.12.2-slim
                    shell: Bash
                    command: export PYTHON_APP_VERSION=$(python get_version.py)
                    privileged: true
                    outputVariables:
                      - name: PYTHON_APP_VERSION
              - stepGroup:
                  name: Scan for Vulnerabilities
                  identifier: Scan_for_Vulnerabilities
                  steps:
                    - parallel:
                        - step:
                            type: Bandit
                            name: Bandit
                            identifier: Bandit
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                name: gabs-redlock-demo
                                variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                              advanced:
                                log:
                                  level: debug
                                fail_on_severity: none
                        - step:
                            type: Gitleaks
                            name: Gitleaks
                            identifier: Gitleaks
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                name: gabs-redlock-demo
                                variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                              advanced:
                                log:
                                  level: debug
                                fail_on_severity: none
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Container
                  identifier: Build_and_Push_Container
                  spec:
                    connectorRef: gabsdh
                    repo: gacerioni/gabs-redlock-demo
                    tags:
                      - latest
                      - <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
              - stepGroup:
                  name: Scan Image
                  identifier: Scan_Image
                  steps:
                    - step:
                        type: AquaTrivy
                        name: AquaTrivy
                        identifier: AquaTrivy
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: container
                            name: gabs-redlock-demo
                            variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                          advanced:
                            log:
                              level: debug
                            fail_on_severity: none
                          privileged: true
                          image:
                            type: docker_v2
                            name: gacerioni/gabs-redlock-demo
                            tag: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
              - step:
                  type: Run
                  name: Final Criteria - Test the container
                  identifier: Final_Test_Do_the_trick
                  spec:
                    shell: Sh
                    command: |-
                      touch /tmp/gabs.csv

                      sleep 1

                      docker run -v /tmp:/tmp \
                        -e "REDIS_CONN_STR=redis://localhost:6379/0" \
                        -e "REDIS_CSV_FILE_NAME=/tmp/gabs.csv" \
                        gacerioni/gabs-redlock-demo:0.0.3-gabs --data "HARNESS TEST!!!"

                      sleep 1

                      cat /tmp/gabs.csv
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: gacerioni/gabs-redlock-demo
        build: <+input>
