pipeline:
  name: Build gabs-redlock-demo
  identifier: Build_gacerioni_gabs_redlock_demo_1708038145151
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Get Python App Version
                  identifier: Get_Python_App_Version
                  spec:
                    connectorRef: gabsdh
                    image: python:3.12.2-slim
                    shell: Bash
                    command: export PYTHON_APP_VERSION=$(python get_version.py)
                    privileged: true
                    outputVariables:
                      - name: PYTHON_APP_VERSION
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Container
                  identifier: Build_and_Push_Container
                  spec:
                    connectorRef: gabsdh
                    repo: gacerioni/gabs-redlock-demo
                    tags:
                      - latest
                      - 0.0.4-gabs
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: gacerioni/gabs-redlock-demo
        build: <+input>
