pipeline:
  name: Build gabs-redlock-demo
  identifier: Build_gacerioni_gabs_redlock_demo_1708038145151
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - stepGroup:
                  name: Redis Background Group
                  identifier: Redis_Background_Group
                  steps:
                    - step:
                        type: Background
                        name: Redis Stack
                        identifier: redis
                        spec:
                          connectorRef: gabsdh
                          image: redis:7.2.4
                          shell: Sh
                          portBindings:
                            "6379": "6379"
                          imagePullPolicy: IfNotPresent
                    - step:
                        type: Run
                        name: Is Redis working
                        identifier: Is_Redis_working
                        spec:
                          shell: Bash
                          command: |-
                            #!/bin/bash
                            sudo apt-get update
                            sudo apt-get install redis-tools -y

                            HOST=localhost
                            PORT=6379
                            RETRIES=5
                            DELAY=2

                            for ((i=0; i<RETRIES; i++)); do
                                if redis-cli -h $HOST -p $PORT ping | grep -q PONG; then
                                    echo "Redis is ready!"
                                    exit 0
                                else
                                    echo "Waiting for Redis to be ready..."
                                    sleep $DELAY
                                fi
                            done

                            echo "Redis is not ready after multiple attempts."
                            exit 1
              - parallel:
                  - step:
                      type: Run
                      name: Get Python App Version
                      identifier: Get_Python_App_Version
                      spec:
                        connectorRef: gabsdh
                        image: python:3.12.2-slim
                        shell: Bash
                        command: export PYTHON_APP_VERSION=$(python get_version.py)
                        privileged: true
                        outputVariables:
                          - name: PYTHON_APP_VERSION
                  - step:
                      type: Run
                      name: Generate Random Secret
                      identifier: Generate_Random_Secret
                      spec:
                        shell: Bash
                        command: export tempsecret=$(echo $RANDOM$RANDOM$RANDOM | cut -c 1-10)
                        outputVariables:
                          - name: tempsecret
              - stepGroup:
                  name: Scan for Vulnerabilities
                  identifier: Scan_for_Vulnerabilities
                  steps:
                    - parallel:
                        - step:
                            type: Bandit
                            name: Bandit
                            identifier: Bandit
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                name: gabs-redlock-demo
                                variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                              advanced:
                                log:
                                  level: debug
                                fail_on_severity: none
                        - step:
                            type: Gitleaks
                            name: Gitleaks
                            identifier: Gitleaks
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                name: gabs-redlock-demo
                                variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                              advanced:
                                log:
                                  level: debug
                                fail_on_severity: none
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
              - stepGroup:
                  name: Testing the App
                  identifier: Testing_the_App
                  steps:
                    - step:
                        type: Run
                        name: Test Happy Path
                        identifier: Test_Happy_Path
                        spec:
                          shell: Sh
                          command: |-
                            touch /tmp/gabs.csv

                            sleep 1

                            export REDIS_CONN_STR=redis://127.0.0.1:6379/0
                            export REDIS_CSV_FILE_NAME=/tmp/gabs.csv

                            python -m pip install -r requirements.txt

                            python main.py --data "HARNESS BUILD PIPELINE BY GABS - "

                            sleep 1

                            cat /tmp/gabs.csv
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Container
                  identifier: Build_and_Push_Container
                  spec:
                    connectorRef: gabsdh
                    repo: gacerioni/gabs-redlock-demo
                    tags:
                      - latest
                      - <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
              - stepGroup:
                  name: Scan Image
                  identifier: Scan_Image
                  steps:
                    - step:
                        type: AquaTrivy
                        name: AquaTrivy
                        identifier: AquaTrivy
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: container
                            name: gabs-redlock-demo
                            variant: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                          advanced:
                            log:
                              level: debug
                            fail_on_severity: none
                          privileged: true
                          image:
                            type: docker_v2
                            name: gacerioni/gabs-redlock-demo
                            tag: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> == "PR"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths:
              - /harness
              - /usr/local/lib/
              - /usr/lib/python3/dist-packages
            key: ""
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: gacerioni/gabs-redlock-demo
        build: <+input>
  variables:
    - name: APP_VERSION
      type: String
      description: ""
      required: false
      value: <+pipeline.stages.Build.spec.execution.steps.Get_Python_App_Version.output.outputVariables.PYTHON_APP_VERSION>
